# Problem Statement

The dataset contains detailed information about residential properties in Ames, Iowa, including physical attributes of the house, quality and condition of various components, spatial measurements, and categorical descriptions such as zoning, neighborhood, and utilities.

However, the raw data is not directly suitable for analysis in its current form. It contains missing values, inconsistent representations, and a mix of categorical and numerical variables that require proper formatting.

The objective of this step is to prepare the dataset into a clean and structured format that is suitable for further analysis. This involves handling missing values, ensuring consistency in feature representations, and organizing variables into a usable form for downstream processing.

## Loading the Data

In [336]:
# Importing necessary libraries and setting display options
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [337]:
# Loading the dataset
df_train = pd.read_csv('../data/raw/train.csv')
df_test = pd.read_csv('../data/raw/test.csv')

In [338]:
# Basic info about the dataset
print(df_train.shape, df_test.shape)

(1460, 81) (1459, 80)

In [339]:
# Checking for missing values in the target variable
df_train['SalePrice'].isna().sum()

np.int64(0)

In [340]:
# Checking if the target variable is present in the test dataset
'SalePrice' in df_test.columns

False

In [341]:
# Combining train and test datasets for EDA
df = pd.concat([df_train, df_test], ignore_index=True)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706.0,Unf,0.0,150.0,856.0,GasA,Ex,Y,SBrkr,856,854,0,1710,1.0,0.0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2.0,548.0,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978.0,Unf,0.0,284.0,1262.0,GasA,Ex,Y,SBrkr,1262,0,0,1262,0.0,1.0,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2.0,460.0,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486.0,Unf,0.0,434.0,920.0,GasA,Ex,Y,SBrkr,920,866,0,1786,1.0,0.0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2.0,608.0,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216.0,Unf,0.0,540.0,756.0,GasA,Gd,Y,SBrkr,961,756,0,1717,1.0,0.0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3.0,642.0,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655.0,Unf,0.0,490.0,1145.0,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1.0,0.0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3.0,836.0,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

# Understanding the data

In [342]:
# Checking the shape of the combined dataset
df.shape

(2919, 81)

In [343]:
# Checking data types of the columns
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning             str
LotFrontage      float64
LotArea            int64
Street               str
Alley                str
LotShape             str
LandContour          str
Utilities            str
LotConfig            str
LandSlope            str
Neighborhood         str
Condition1           str
Condition2           str
BldgType             str
HouseStyle           str
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle            str
RoofMatl             str
Exterior1st          str
Exterior2nd          str
MasVnrType           str
MasVnrArea       float64
ExterQual            str
ExterCond            str
Foundation           str
BsmtQual             str
BsmtCond             str
BsmtExposure         str
BsmtFinType1         str
BsmtFinSF1       float64
BsmtFinType2         str
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
Heating              str
HeatingQC            str
CentralAir           str
Electrical           str
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath     float64
BsmtHalfBath     float64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual          str
TotRmsAbvGrd       int64
Functional           str
Fireplaces         int64
FireplaceQu          str
GarageType           str
GarageYrBlt      float64
GarageFinish         str
GarageCars       float64
GarageArea       float64
GarageQual           str
GarageCond           str
PavedDrive           str
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC               str
Fence                str
MiscFeature          str
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType             str
SaleCondition        str
SalePrice        float64
dtype: object

In [344]:
# Analyzing categorical columns
for col in df.columns:
    if(df[col].dtype == 'string'):
        print(f"\n{col.upper()}")
        print(df[col].value_counts())

MSZONING
MSZoning
RL         2265
RM          460
FV          139
RH           26
C (all)      25
Name: count, dtype: int64

STREET
Street
Pave    2907
Grvl      12
Name: count, dtype: int64

ALLEY
Alley
Grvl    120
Pave     78
Name: count, dtype: int64

LOTSHAPE
LotShape
Reg    1859
IR1     968
IR2      76
IR3      16
Name: count, dtype: int64

LANDCONTOUR
LandContour
Lvl    2622
HLS     120
Bnk     117
Low      60
Name: count, dtype: int64

UTILITIES
Utilities
AllPub    2916
NoSeWa       1
Name: count, dtype: int64

LOTCONFIG
LotConfig
Inside     2133
Corner      511
CulDSac     176
FR2          85
FR3          14
Name: count, dtype: int64

LANDSLOPE
LandSlope
Gtl    2778
Mod     125
Sev      16
Name: count, dtype: int64

NEIGHBORHOOD
Neighborhood
NAmes      443
CollgCr    267
OldTown    239
Edwards    194
Somerst    182
NridgHt    166
Gilbert    165
Sawyer     151
NWAmes     131
SawyerW    125
Mitchel    114
BrkSide    108
Crawfor    103
IDOTRR      93
Timber      72
NoRidge     71
StoneBr     51
SWISU       48
ClearCr     44
MeadowV     37
BrDale      30
Blmngtn     28
Veenker     24
NPkVill     23
Blueste     10
Name: count, dtype: int64

CONDITION1
Condition1
Norm      2511
Feedr      164
Artery      92
RRAn        50
PosN        39
RRAe        28
PosA        20
RRNn         9
RRNe         6
Name: count, dtype: int64

CONDITION2
Condition2
Norm      2889
Feedr       13
Artery       5
PosN         4
PosA         4
RRNn         2
RRAn         1
RRAe         1
Name: count, dtype: int64

BLDGTYPE
BldgType
1Fam      2425
TwnhsE     227
Duplex     109
Twnhs       96
2fmCon      62
Name: count, dtype: int64

HOUSESTYLE
HouseStyle
1Story    1471
2Story     872
1.5Fin     314
SLvl       128
SFoyer      83
2.5Unf      24
1.5Unf      19
2.5Fin       8
Name: count, dtype: int64

ROOFSTYLE
RoofStyle
Gable      2310
Hip         551
Gambrel      22
Flat         20
Mansard      11
Shed          5
Name: count, dtype: int64

ROOFMATL
RoofMatl
CompShg    2876
Tar&Grv      23
WdShake       9
WdShngl       7
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

EXTERIOR1ST
Exterior1st
VinylSd    1025
MetalSd     450
HdBoard     442
Wd Sdng     411
Plywood     221
CemntBd     126
BrkFace      87
WdShing      56
AsbShng      44
Stucco       43
BrkComm       6
AsphShn       2
Stone         2
CBlock        2
ImStucc       1
Name: count, dtype: int64

EXTERIOR2ND
Exterior2nd
VinylSd    1014
MetalSd     447
HdBoard     406
Wd Sdng     391
Plywood     270
CmentBd     126
Wd Shng      81
BrkFace      47
Stucco       47
AsbShng      38
Brk Cmn      22
ImStucc      15
Stone         6
AsphShn       4
CBlock        3
Other         1
Name: count, dtype: int64

MASVNRTYPE
MasVnrType
BrkFace    879
Stone      249
BrkCmn      25
Name: count, dtype: int64

EXTERQUAL
ExterQual
TA    1798
Gd     979
Ex     107
Fa      35
Name: count, dtype: int64

EXTERCOND
ExterCond
TA    2538
Gd     299
Fa      67
Ex      12
Po       3
Name: count, dtype: int64

FOUNDATION
Foundation
PConc     1308
CBlock    1235
BrkTil     311
Slab        49
Stone       11
Wood         5
Name: count, dtype: int64

BSMTQUAL
BsmtQual
TA    1283
Gd    1209
Ex     258
Fa      88
Name: count, dtype: int64

BSMTCOND
BsmtCond
TA    2606
Gd     122
Fa     104
Po       5
Name: count, dtype: int64

BSMTEXPOSURE
BsmtExposure
No    1904
Av     418
Gd     276
Mn     239
Name: count, dtype: int64

BSMTFINTYPE1
BsmtFinType1
Unf    851
GLQ    849
ALQ    429
Rec    288
BLQ    269
LwQ    154
Name: count, dtype: int64

BSMTFINTYPE2
BsmtFinType2
Unf    2493
Rec     105
LwQ      87
BLQ      68
ALQ      52
GLQ      34
Name: count, dtype: int64

HEATING
Heating
GasA     2874
GasW       27
Grav        9
Wall        6
OthW        2
Floor       1
Name: count, dtype: int64

HEATINGQC
HeatingQC
Ex    1493
TA     857
Gd     474
Fa      92
Po       3
Name: count, dtype: int64

CENTRALAIR
CentralAir
Y    2723
N     196
Name: count, dtype: int64

ELECTRICAL
Electrical
SBrkr    2671
FuseA     188
FuseF      50
FuseP       8
Mix         1
Name: count, dtype: int64

KITCHENQUAL
KitchenQual
TA    1492
Gd    1151
Ex     205
Fa      70
Name: count, dtype: int64

FUNCTIONAL
Functional
Typ     2717
Min2      70
Min1      65
Mod       35
Maj1      19
Maj2       9
Sev        2
Name: count, dtype: int64

FIREPLACEQU
FireplaceQu
Gd    744
TA    592
Fa     74
Po     46
Ex     43
Name: count, dtype: int64

GARAGETYPE
GarageType
Attchd     1723
Detchd      779
BuiltIn     186
Basment      36
2Types       23
CarPort      15
Name: count, dtype: int64

GARAGEFINISH
GarageFinish
Unf    1230
RFn     811
Fin     719
Name: count, dtype: int64

GARAGEQUAL
GarageQual
TA    2604
Fa     124
Gd      24
Po       5
Ex       3
Name: count, dtype: int64

GARAGECOND
GarageCond
TA    2654
Fa      74
Gd      15
Po      14
Ex       3
Name: count, dtype: int64

PAVEDDRIVE
PavedDrive
Y    2641
N     216
P      62
Name: count, dtype: int64

POOLQC
PoolQC
Ex    4
Gd    4
Fa    2
Name: count, dtype: int64

FENCE
Fence
MnPrv    329
GdPrv    118
GdWo     112
MnWw      12
Name: count, dtype: int64

MISCFEATURE
MiscFeature
Shed    95
Gar2     5
Othr     4
TenC     1
Name: count, dtype: int64

SALETYPE
SaleType
WD       2525
New       239
COD        87
ConLD      26
CWD        12
ConLI       9
ConLw       8
Oth         7
Con         5
Name: count, dtype: int64

SALECONDITION
SaleCondition
Normal     2402
Partial     245
Abnorml     190
Family       46
Alloca       24
AdjLand      12
Name: count, dtype: int64

In [345]:
# Analyzing numerical columns
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,2918.000000,2918.000000,2918.000000,2919.000000,2919.000000,2919.000000,2919.000000,2917.000000,2917.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2760.000000,2918.000000,2918.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,1460.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,49.582248,560.772104,1051.777587,1159.581706,336.483727,4.694416,1500.759849,0.429894,0.061364,1.568003,0.380267,2.860226,1.044536,6.451524,0.597122,1978.113406,1.766621,472.874572,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,169.205611,439.543659,440.766258,392.362079,428.701456,46.396825,506.051045,0.524736,0.245687,0.552969,0.502872,0.822693,0.214462,1.569379,0.646129,25.574285,0.761624,215.394815,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,334.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1895.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,730.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,0.000000,220.000000,793.000000,876.000000,0.000000,0.000000,1126.000000,0.000000,0.000000,1.000000,0.000000,2.000000,1.000000,5.000000,0.000000,1960.000000,1.000000,320.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,1460.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,0.000000,467.000000,989.500000,1082.000000,0.000000,0.000000,1444.000000,0.000000,0.000000,2.000000,0.000000,3.000000,1.000000,6.000000,1.000000,1979.000000,2.000000,480.000000,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,2189.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,0.000000,805.500000,1302.000000,1387.500000,704.000000,0.000000,1743.500000,1.000000,0.000000,2.000000,1.000000,3.000000,1.000000,7.000000,1.000000,2002.000000,2.000000,576.000000,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,2919.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1526.000000,2336.000000,6110.000000,5095.000000,2065.000000,1064.000000,5642.000000,3.000000,2.000000,4.000000,2.000000,8.000000,3.000000,15.000000,4.000000,2207.000000,5.000000,1488.000000,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

## Data Quality Assessment

In [346]:
# Checking for negative values in numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in numerical_cols:
    if (df[col] < 0).any():
        print(f"{col} has negative values")

In [347]:
# Checking duplicated rows
df.duplicated().sum()

np.int64(0)

In [348]:
# Primary key columns should not have duplicates, checking for that
primary_key_cols = ['Id']
for col in primary_key_cols:
    if df[col].duplicated().any():
        print(f"{col} has duplicate values")

In [349]:
# Data type validation
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning             str
LotFrontage      float64
LotArea            int64
Street               str
Alley                str
LotShape             str
LandContour          str
Utilities            str
LotConfig            str
LandSlope            str
Neighborhood         str
Condition1           str
Condition2           str
BldgType             str
HouseStyle           str
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle            str
RoofMatl             str
Exterior1st          str
Exterior2nd          str
MasVnrType           str
MasVnrArea       float64
ExterQual            str
ExterCond            str
Foundation           str
BsmtQual             str
BsmtCond             str
BsmtExposure         str
BsmtFinType1         str
BsmtFinSF1       float64
BsmtFinType2         str
BsmtFinSF2       float64
BsmtUnfSF        float64
TotalBsmtSF      float64
Heating              str
HeatingQC            str
CentralAir           str
Electrical           str
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath     float64
BsmtHalfBath     float64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
KitchenQual          str
TotRmsAbvGrd       int64
Functional           str
Fireplaces         int64
FireplaceQu          str
GarageType           str
GarageYrBlt      float64
GarageFinish         str
GarageCars       float64
GarageArea       float64
GarageQual           str
GarageCond           str
PavedDrive           str
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
PoolQC               str
Fence                str
MiscFeature          str
MiscVal            int64
MoSold             int64
YrSold             int64
SaleType             str
SaleCondition        str
SalePrice        float64
dtype: object

In [350]:
# Invalid / Illogical values in the dataset
df[df["YrSold"] < df["YearBuilt"]][["Id", "YearBuilt", "YrSold"]]

        Id  YearBuilt  YrSold
2549  2550       2008    2007

In [351]:
# Invalid / Illogical values in the dataset
df[df['MoSold'] > 12][['Id', 'MoSold']]
df[df['MoSold'] < 1][['Id', 'MoSold']]

Empty DataFrame
Columns: [Id, MoSold]
Index: []

In [352]:
# Invalid / Illogical values in the dataset
df[df["YrSold"] < df["YearRemodAdd"]][["Id", "YearRemodAdd", "YrSold"]]

        Id  YearRemodAdd  YrSold
523    524          2008    2007
2295  2296          2008    2007
2549  2550          2009    2007

In [353]:
# Checking for missing values in the dataset
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

PoolQC           99.657417
MiscFeature      96.402878
Alley            93.216855
Fence            80.438506
MasVnrType       60.500171
SalePrice        49.982871
FireplaceQu      48.646797
LotFrontage      16.649538
GarageYrBlt       5.447071
GarageFinish      5.447071
GarageQual        5.447071
GarageCond        5.447071
GarageType        5.378554
BsmtExposure      2.809181
BsmtCond          2.809181
BsmtQual          2.774923
BsmtFinType2      2.740665
BsmtFinType1      2.706406
MasVnrArea        0.787941
MSZoning          0.137033
Functional        0.068517
BsmtFullBath      0.068517
Utilities         0.068517
BsmtHalfBath      0.068517
Electrical        0.034258
TotalBsmtSF       0.034258
BsmtUnfSF         0.034258
KitchenQual       0.034258
BsmtFinSF2        0.034258
BsmtFinSF1        0.034258
SaleType          0.034258
GarageCars        0.034258
Exterior2nd       0.034258
Exterior1st       0.034258
GarageArea        0.034258
YrSold            0.000000
Fireplaces        0.000000
MoSold            0.000000
MiscVal           0.000000
SaleCondition     0.000000
TotRmsAbvGrd      0.000000
PoolArea          0.000000
3SsnPorch         0.000000
ScreenPorch       0.000000
EnclosedPorch     0.000000
OpenPorchSF       0.000000
WoodDeckSF        0.000000
PavedDrive        0.000000
BedroomAbvGr      0.000000
KitchenAbvGr      0.000000
Id                0.000000
HalfBath          0.000000
FullBath          0.000000
LotArea           0.000000
Street            0.000000
LotShape          0.000000
LandContour       0.000000
LotConfig         0.000000
LandSlope         0.000000
Neighborhood      0.000000
Condition1        0.000000
Condition2        0.000000
BldgType          0.000000
HouseStyle        0.000000
OverallQual       0.000000
OverallCond       0.000000
YearBuilt         0.000000
YearRemodAdd      0.000000
RoofStyle         0.000000
RoofMatl          0.000000
ExterQual         0.000000
ExterCond         0.000000
Foundation        0.000000
Heating           0.000000
MSSubClass        0.000000
CentralAir        0.000000
1stFlrSF          0.000000
2ndFlrSF          0.000000
LowQualFinSF      0.000000
GrLivArea         0.000000
HeatingQC         0.000000
dtype: float64

In [354]:
# Checking for illogical values in the dataset, such as garage year built being greater than the year sold
df[df["GarageYrBlt"] > df["YrSold"]][["Id", "GarageYrBlt", "YrSold"]]

        Id  GarageYrBlt  YrSold
2549  2550       2008.0    2007
2592  2593       2207.0    2007

## Data Preparation

In [355]:
# Fixing missing values in categorical columns by filling them with 'NA' as per the description of the dataset
columns_with_NA = ['Alley', 'PoolQC', 'Fence', 'MiscFeature', 'MasVnrType', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']
for col in columns_with_NA:
    df[col] = df[col].fillna('NA')

In [356]:
# Fixing missing values in numerical columns
df['LotFrontage'] = df['LotFrontage'].fillna(df['LotFrontage'].median())
df.loc[df["GarageType"] == 'NA', "GarageYrBlt"] = 0
df.loc[df["MasVnrType"] == 'NA', "MasVnrArea"] = 0

In [357]:
df[df['GarageYrBlt'].isna()][['GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'GarageArea', 'GarageCars']]

# Fix special garage cases

# Row 2126: Garage clearly exists
df.loc[2126, "GarageYrBlt"] = df.loc[2126, "YearBuilt"]
df.loc[2126, "GarageFinish"] = df["GarageFinish"].mode()[0]
df.loc[2126, "GarageQual"] = "TA"
df.loc[2126, "GarageCond"] = "TA"

# Statistics for detached garages
detchd_cars_median = df.loc[
    (df["GarageType"] == "Detchd") & (df["GarageCars"].notna()),
    "GarageCars"
].median()

detchd_area_median = df.loc[
    (df["GarageType"] == "Detchd") & (df["GarageArea"].notna()),
    "GarageArea"
].median()

# Row 2576: GarageType exists but other details are missing
df.loc[2576, "GarageYrBlt"] = df.loc[2576, "YearBuilt"]
df.loc[2576, "GarageFinish"] = df["GarageFinish"].mode()[0]
df.loc[2576, "GarageQual"] = "TA"
df.loc[2576, "GarageCond"] = "TA"
df.loc[2576, "GarageCars"] = detchd_cars_median
df.loc[2576, "GarageArea"] = detchd_area_median

# Handle true "No Garage" rows

garage_cat_cols = [
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond"
]

garage_num_cols = [
    "GarageYrBlt",
    "GarageArea",
    "GarageCars"
]

for col in garage_cat_cols:
    df[col] = df[col].fillna("None")

for col in garage_num_cols:
    df[col] = df[col].fillna(0)

In [358]:
# Handling smaller percentage of missing values in MSZoning by filling them with the mode
df["MSZoning"] = df["MSZoning"].fillna(df["MSZoning"].mode()[0])

In [359]:
# Investigating missing values in basement-related columns
df.loc[df["BsmtHalfBath"].isna(),
       ["BsmtQual", "BsmtCond", "BsmtExposure",
        "BsmtFinType1", "BsmtFinType2"]]

df.loc[df["BsmtHalfBath"].isna(), "BsmtHalfBath"] = 0
df.loc[df["BsmtFullBath"].isna(), "BsmtFullBath"] = 0

In [360]:
# For Functional missing values, since the percentage is very small, we can fill them with the mode which is 'Typ'
df.loc[df['Functional'].isna(), 'Functional'] = 'Typ'

In [361]:
# For Utilities, since the percentage is very small, we can fill them with the mode which is 'AllPub'
df["Utilities"] = df["Utilities"].fillna(
    df["Utilities"].mode()[0]
)

In [362]:
# Investigating missing values in basement area-related columns
df[df['BsmtUnfSF'].isna()][['BsmtQual']]
df['TotalBsmtSF'] = df['TotalBsmtSF'].fillna(0)
df['BsmtFinSF2'] = df['BsmtFinSF2'].fillna(0)
df['BsmtFinSF1'] = df['BsmtFinSF1'].fillna(0)
df['BsmtUnfSF'] = df['BsmtUnfSF'].fillna(0)

In [363]:
# For the remaining categorical columns with missing values, since the percentage is very small, we can fill them with the mode
for col in ["KitchenQual", "Exterior1st", "Exterior2nd", "Electrical", "SaleType"]:
    df[col] = df[col].fillna(df[col].mode()[0])

In [364]:
# Checking for missing values in the dataset after handling them
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

SalePrice        49.982871
CentralAir        0.000000
GarageYrBlt       0.000000
GarageType        0.000000
FireplaceQu       0.000000
Fireplaces        0.000000
Functional        0.000000
TotRmsAbvGrd      0.000000
KitchenQual       0.000000
KitchenAbvGr      0.000000
BedroomAbvGr      0.000000
HalfBath          0.000000
FullBath          0.000000
BsmtHalfBath      0.000000
BsmtFullBath      0.000000
GrLivArea         0.000000
LowQualFinSF      0.000000
2ndFlrSF          0.000000
1stFlrSF          0.000000
GarageFinish      0.000000
GarageCars        0.000000
GarageArea        0.000000
PoolQC            0.000000
SaleCondition     0.000000
SaleType          0.000000
YrSold            0.000000
MoSold            0.000000
MiscVal           0.000000
MiscFeature       0.000000
Fence             0.000000
PoolArea          0.000000
GarageQual        0.000000
ScreenPorch       0.000000
3SsnPorch         0.000000
EnclosedPorch     0.000000
OpenPorchSF       0.000000
WoodDeckSF        0.000000
PavedDrive        0.000000
GarageCond        0.000000
Electrical        0.000000
Id                0.000000
MSSubClass        0.000000
Heating           0.000000
OverallCond       0.000000
OverallQual       0.000000
HouseStyle        0.000000
BldgType          0.000000
Condition2        0.000000
Condition1        0.000000
Neighborhood      0.000000
LandSlope         0.000000
LotConfig         0.000000
Utilities         0.000000
LandContour       0.000000
LotShape          0.000000
Alley             0.000000
Street            0.000000
LotArea           0.000000
LotFrontage       0.000000
MSZoning          0.000000
YearBuilt         0.000000
YearRemodAdd      0.000000
RoofStyle         0.000000
BsmtCond          0.000000
TotalBsmtSF       0.000000
BsmtUnfSF         0.000000
BsmtFinSF2        0.000000
BsmtFinType2      0.000000
BsmtFinSF1        0.000000
BsmtFinType1      0.000000
BsmtExposure      0.000000
BsmtQual          0.000000
RoofMatl          0.000000
Foundation        0.000000
ExterCond         0.000000
ExterQual         0.000000
MasVnrArea        0.000000
MasVnrType        0.000000
Exterior2nd       0.000000
Exterior1st       0.000000
HeatingQC         0.000000
dtype: float64

## Encoding for modelling

In [365]:
# Creating quality maps for reasonable ordinal categorical variables
quality_map_streets = {
    "Grvl": 0,
    "Pave": 1
}

quality_map_alley = {
    "NA": 0,
    "Grvl": 1,
    "Pave": 2
}

quality_map_utilities = {
    "ELO": 0,
    "NoSeWa": 1,
    "NoSewr": 2,
    "AllPub": 3
}

quality_map_LotShape = {
    "Reg": 3,
    "IR1": 2,
    "IR2": 1,
    "IR3": 0
}

quality_map_LandSlope = {
    "Sev": 0,
    "Mod": 1,
    "Gtl": 2
}

quality_map_ExterQual = {
    "Po": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
}

quality_map_ExterCond = {
    "Po": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
}

quality_map_BsmtQual = {
    "NA": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

quality_map_BsmtCond = {
    "NA": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

quality_map_BsmtExposure = {
    "NA": 0,
    "No": 1,
    "Mn": 2,
    "Av": 3,
    "Gd": 4
}

quality_map_BsmtFinType1 = {
    "NA": 0,
    "Unf": 1,
    "LwQ": 2,
    "Rec": 3,
    "BLQ": 4,
    "ALQ": 5,
    "GLQ": 6
}

quality_map_BsmtFinType2 = quality_map_BsmtFinType1

quality_map_HeatingQC = {
    "Po": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
}

quality_map_CentralAir = {
    "N": 0,
    "Y": 1
}

quality_map_Electrical = {
    "Mix": 0,
    "FuseP": 1,
    "FuseF": 2,
    "FuseA": 3,
    "SBrkr": 4
}

quality_map_KitchenQual = {
    "Po": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
}

quality_map_Functional = {
    "Sal": 0,
    "Sev": 1,
    "Maj2": 2,
    "Maj1": 3,
    "Mod": 4,
    "Min2": 5,
    "Min1": 6,
    "Typ": 7
}

quality_map_FireplaceQu = {
    "NA": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

quality_map_GarageFinish = {
    "NA": 0,
    "Unf": 1,
    "RFn": 2,
    "Fin": 3
}

quality_map_GarageQual = {
    "NA": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

quality_map_GarageCond = quality_map_GarageQual

quality_map_PavedDrive = {
    "N": 0,
    "P": 1,
    "Y": 2
}

quality_maps_PoolQC = {
    "NA": 0,
    "Fa": 1,
    "TA": 2,
    "Gd": 3,
    "Ex": 4
}

quality_maps_Fence = {
    "NA": 0,
    "MnWw": 1,
    "GdWo": 2,
    "MnPrv": 3,
    "GdPrv": 4
}

In [366]:
# Mapping the quality maps to the respective columns in the dataset
df['Street'] = df['Street'].map(quality_map_streets)
df['Alley'] = df['Alley'].map(quality_map_alley)
df['Utilities'] = df['Utilities'].map(quality_map_utilities)
df['LotShape'] = df['LotShape'].map(quality_map_LotShape)
df['LandSlope'] = df['LandSlope'].map(quality_map_LandSlope)
df['Functional'] = df['Functional'].map(quality_map_Functional)
df['FireplaceQu'] = df['FireplaceQu'].map(quality_map_FireplaceQu)
df['GarageFinish'] = df['GarageFinish'].map(quality_map_GarageFinish)
df['GarageQual'] = df['GarageQual'].map(quality_map_GarageQual)
df['GarageCond'] = df['GarageCond'].map(quality_map_GarageCond)
df['PavedDrive'] = df['PavedDrive'].map(quality_map_PavedDrive)
df['PoolQC'] = df['PoolQC'].map(quality_maps_PoolQC)
df['Fence'] = df['Fence'].map(quality_maps_Fence)

In [367]:
# Ordinal encode remaining categorical features
cat_cols = df.select_dtypes(include="string").columns
df = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=False,
    dtype=int
)

In [368]:
# Checking data types of the columns after encoding
df.dtypes

Id                         int64
MSSubClass                 int64
LotFrontage              float64
LotArea                    int64
Street                     int64
Alley                      int64
LotShape                   int64
Utilities                  int64
LandSlope                  int64
OverallQual                int64
OverallCond                int64
YearBuilt                  int64
YearRemodAdd               int64
MasVnrArea               float64
BsmtFinSF1               float64
BsmtFinSF2               float64
BsmtUnfSF                float64
TotalBsmtSF              float64
1stFlrSF                   int64
2ndFlrSF                   int64
LowQualFinSF               int64
GrLivArea                  int64
BsmtFullBath             float64
BsmtHalfBath             float64
FullBath                   int64
HalfBath                   int64
BedroomAbvGr               int64
KitchenAbvGr               int64
TotRmsAbvGrd               int64
Functional                 int64
Fireplaces                 int64
FireplaceQu                int64
GarageYrBlt              float64
GarageFinish               int64
GarageCars               float64
GarageArea               float64
GarageQual                 int64
GarageCond                 int64
PavedDrive                 int64
WoodDeckSF                 int64
OpenPorchSF                int64
EnclosedPorch              int64
3SsnPorch                  int64
ScreenPorch                int64
PoolArea                   int64
PoolQC                     int64
Fence                      int64
MiscVal                    int64
MoSold                     int64
YrSold                     int64
SalePrice                float64
MSZoning_C (all)           int64
MSZoning_FV                int64
MSZoning_RH                int64
MSZoning_RL                int64
MSZoning_RM                int64
LandContour_Bnk            int64
LandContour_HLS            int64
LandContour_Low            int64
LandContour_Lvl            int64
LotConfig_Corner           int64
LotConfig_CulDSac          int64
LotConfig_FR2              int64
LotConfig_FR3              int64
LotConfig_Inside           int64
Neighborhood_Blmngtn       int64
Neighborhood_Blueste       int64
Neighborhood_BrDale        int64
Neighborhood_BrkSide       int64
Neighborhood_ClearCr       int64
Neighborhood_CollgCr       int64
Neighborhood_Crawfor       int64
Neighborhood_Edwards       int64
Neighborhood_Gilbert       int64
Neighborhood_IDOTRR        int64
Neighborhood_MeadowV       int64
Neighborhood_Mitchel       int64
Neighborhood_NAmes         int64
Neighborhood_NPkVill       int64
Neighborhood_NWAmes        int64
Neighborhood_NoRidge       int64
Neighborhood_NridgHt       int64
Neighborhood_OldTown       int64
Neighborhood_SWISU         int64
Neighborhood_Sawyer        int64
Neighborhood_SawyerW       int64
Neighborhood_Somerst       int64
Neighborhood_StoneBr       int64
Neighborhood_Timber        int64
Neighborhood_Veenker       int64
Condition1_Artery          int64
Condition1_Feedr           int64
Condition1_Norm            int64
Condition1_PosA            int64
Condition1_PosN            int64
Condition1_RRAe            int64
Condition1_RRAn            int64
Condition1_RRNe            int64
Condition1_RRNn            int64
Condition2_Artery          int64
Condition2_Feedr           int64
Condition2_Norm            int64
Condition2_PosA            int64
Condition2_PosN            int64
Condition2_RRAe            int64
Condition2_RRAn            int64
Condition2_RRNn            int64
BldgType_1Fam              int64
BldgType_2fmCon            int64
BldgType_Duplex            int64
BldgType_Twnhs             int64
BldgType_TwnhsE            int64
HouseStyle_1.5Fin          int64
HouseStyle_1.5Unf          int64
HouseStyle_1Story          int64
HouseStyle_2.5Fin          int64
HouseStyle_2.5Unf          int64
HouseStyle_2Story          int64
HouseStyle_SFoyer          int64
HouseStyle_SLvl            int64
RoofStyle_Flat             int64
RoofStyle_Gable            int64
RoofStyle_Gambrel          int64
RoofStyle_Hip              int64
RoofStyle_Mansard          int64
RoofStyle_Shed             int64
RoofMatl_ClyTile           int64
RoofMatl_CompShg           int64
RoofMatl_Membran           int64
RoofMatl_Metal             int64
RoofMatl_Roll              int64
RoofMatl_Tar&Grv           int64
RoofMatl_WdShake           int64
RoofMatl_WdShngl           int64
Exterior1st_AsbShng        int64
Exterior1st_AsphShn        int64
Exterior1st_BrkComm        int64
Exterior1st_BrkFace        int64
Exterior1st_CBlock         int64
Exterior1st_CemntBd        int64
Exterior1st_HdBoard        int64
Exterior1st_ImStucc        int64
Exterior1st_MetalSd        int64
Exterior1st_Plywood        int64
Exterior1st_Stone          int64
Exterior1st_Stucco         int64
Exterior1st_VinylSd        int64
Exterior1st_Wd Sdng        int64
Exterior1st_WdShing        int64
Exterior2nd_AsbShng        int64
Exterior2nd_AsphShn        int64
Exterior2nd_Brk Cmn        int64
Exterior2nd_BrkFace        int64
Exterior2nd_CBlock         int64
Exterior2nd_CmentBd        int64
Exterior2nd_HdBoard        int64
Exterior2nd_ImStucc        int64
Exterior2nd_MetalSd        int64
Exterior2nd_Other          int64
Exterior2nd_Plywood        int64
Exterior2nd_Stone          int64
Exterior2nd_Stucco         int64
Exterior2nd_VinylSd        int64
Exterior2nd_Wd Sdng        int64
Exterior2nd_Wd Shng        int64
MasVnrType_BrkCmn          int64
MasVnrType_BrkFace         int64
MasVnrType_NA              int64
MasVnrType_Stone           int64
ExterQual_Ex               int64
ExterQual_Fa               int64
ExterQual_Gd               int64
ExterQual_TA               int64
ExterCond_Ex               int64
ExterCond_Fa               int64
ExterCond_Gd               int64
ExterCond_Po               int64
ExterCond_TA               int64
Foundation_BrkTil          int64
Foundation_CBlock          int64
Foundation_PConc           int64
Foundation_Slab            int64
Foundation_Stone           int64
Foundation_Wood            int64
BsmtQual_Ex                int64
BsmtQual_Fa                int64
BsmtQual_Gd                int64
BsmtQual_NA                int64
BsmtQual_TA                int64
BsmtCond_Fa                int64
BsmtCond_Gd                int64
BsmtCond_NA                int64
BsmtCond_Po                int64
BsmtCond_TA                int64
BsmtExposure_Av            int64
BsmtExposure_Gd            int64
BsmtExposure_Mn            int64
BsmtExposure_NA            int64
BsmtExposure_No            int64
BsmtFinType1_ALQ           int64
BsmtFinType1_BLQ           int64
BsmtFinType1_GLQ           int64
BsmtFinType1_LwQ           int64
BsmtFinType1_NA            int64
BsmtFinType1_Rec           int64
BsmtFinType1_Unf           int64
BsmtFinType2_ALQ           int64
BsmtFinType2_BLQ           int64
BsmtFinType2_GLQ           int64
BsmtFinType2_LwQ           int64
BsmtFinType2_NA            int64
BsmtFinType2_Rec           int64
BsmtFinType2_Unf           int64
Heating_Floor              int64
Heating_GasA               int64
Heating_GasW               int64
Heating_Grav               int64
Heating_OthW               int64
Heating_Wall               int64
HeatingQC_Ex               int64
HeatingQC_Fa               int64
HeatingQC_Gd               int64
HeatingQC_Po               int64
HeatingQC_TA               int64
CentralAir_N               int64
CentralAir_Y               int64
Electrical_FuseA           int64
Electrical_FuseF           int64
Electrical_FuseP           int64
Electrical_Mix             int64
Electrical_SBrkr           int64
KitchenQual_Ex             int64
KitchenQual_Fa             int64
KitchenQual_Gd             int64
KitchenQual_TA             int64
GarageType_2Types          int64
GarageType_Attchd          int64
GarageType_Basment         int64
GarageType_BuiltIn         int64
GarageType_CarPort         int64
GarageType_Detchd          int64
GarageType_NA              int64
MiscFeature_Gar2           int64
MiscFeature_NA             int64
MiscFeature_Othr           int64
MiscFeature_Shed           int64
MiscFeature_TenC           int64
SaleType_COD               int64
SaleType_CWD               int64
SaleType_Con               int64
SaleType_ConLD             int64
SaleType_ConLI             int64
SaleType_ConLw             int64
SaleType_New               int64
SaleType_Oth               int64
SaleType_WD                int64
SaleCondition_Abnorml      int64
SaleCondition_AdjLand      int64
SaleCondition_Alloca       int64
SaleCondition_Family       int64
SaleCondition_Normal       int64
SaleCondition_Partial      int64
dtype: object

## Feature Engineering

In [369]:
# Making meaningful features based on domain knowledge, intuition and dataset description
df["TotalSF"] = (
    df["TotalBsmtSF"]
    + df["1stFlrSF"]
    + df["2ndFlrSF"]
)

# Total bathrooms is a more meaningful feature than individual bathroom features, and it also captures the half bathrooms as 0.5 which is more intuitive
df["TotalBath"] = (
    df["FullBath"]
    + 0.5 * df["HalfBath"]
    + df["BsmtFullBath"]
    + 0.5 * df["BsmtHalfBath"]
)

# Age of the house at the time of sale is more meaningful than the year it was built, 0 if the houseage comes out to be negative which can happen in some cases where the house was remodeled and the year of remodel is greater than the year of sale
df["HouseAge"] = df["YrSold"] - df["YearBuilt"]
df.loc[df["HouseAge"] < 0, "HouseAge"] = 0


# Years since remodel is more meaningful than the year it was remodeled, 0 if the years since remodel comes out to be negative which can happen in some cases where the house was remodeled after it was sold
df["YearsSinceRemodel"] = (
    df["YrSold"] - df["YearRemodAdd"]
)
df.loc[df["YearsSinceRemodel"] < 0, "YearsSinceRemodel"] = 0

# Total porch area is more meaningful than individual porch features
df["TotalPorchSF"] = (
    df["OpenPorchSF"]
    + df["EnclosedPorch"]
    + df["3SsnPorch"]
    + df["ScreenPorch"]
)

# Outdoor area is more meaningful than individual outdoor features
df["OutdoorSF"] = (
    df["WoodDeckSF"]
    + df["OpenPorchSF"]
    + df["EnclosedPorch"]
    + df["3SsnPorch"]
    + df["ScreenPorch"]
)

# Total basement finished area is more meaningful than individual basement finished area features
df["TotalBsmtFinished"] = (
    df["BsmtFinSF1"]
    + df["BsmtFinSF2"]
)

# Total rooms above ground is more meaningful than individual room features, and it also captures the number of bedrooms which is an important feature for house prices
df["TotalRooms"] = (
    df["TotRmsAbvGrd"]
    + df["BedroomAbvGr"]
)

# Total property area is more meaningful than individual area features, and it also captures the garage area which is an important feature for house prices
df["TotalPropertySF"] = (
    df["TotalSF"]
    + df["GarageArea"]
)

# Whether the house has a garage, basement or pool is more meaningful than the area of these features, and it also captures the cases where the area is 0 but the feature exists which can be important for house prices
df["HasGarage"] = (
    df["GarageArea"] > 0
).astype(int)

# Whether the house has a basement is more meaningful than the area of the basement, and it also captures the cases where the area is 0 but the feature exists which can be important for house prices
df["HasBasement"] = (
    df["TotalBsmtSF"] > 0
).astype(int)

# Whether the house has a pool is more meaningful than the area of the pool, and it also captures the cases where the area is 0 but the feature exists which can be important for house prices
df["HasPool"] = (
    df["PoolArea"] > 0
).astype(int)

# A combined feature of quality and area can be more meaningful than individual features, as it captures the interaction between these features which can be important for house prices
df["QualitySF"] = (
    df["OverallQual"] * df["TotalSF"]
)

# Bringing the target variable to the end of the dataframe for better readability
cols = [col for col in df.columns if col != "SalePrice"] + ["SalePrice"]
df = df[cols]

In [370]:
# ML ready dataset export
df_train = df[df['SalePrice'].notna()]
df_test = df[df['SalePrice'].isna()].drop(columns=['SalePrice'])
df_train.to_csv('../data/processed/house_price_dataset_train.csv', index=False)
df_test.to_csv('../data/processed/house_price_dataset_test.csv', index=False)
df_train.head()

,Id,MSSubClass,LotFrontage,LotArea,Street,Alley,LotShape,Utilities,LandSlope,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscVal,MoSold,YrSold,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LandContour_Bnk,LandContour_HLS,LandContour_Low,LandContour_Lvl,LotConfig_Corner,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_IDOTRR,Neighborhood_MeadowV,Neighborhood_Mitchel,Neighborhood_NAmes,Neighborhood_NPkVill,Neighborhood_NWAmes,Neighborhood_NoRidge,Neighborhood_NridgHt,Neighborhood_OldTown,Neighborhood_SWISU,Neighborhood_Sawyer,Neighborhood_SawyerW,Neighborhood_Somerst,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,Condition1_Artery,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Artery,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Fin,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Flat,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_ClyTile,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Exterior1st_AsbShng,Exterior1st_AsphShn,Exterior1st_BrkComm,Exterior1st_BrkFace,Exterior1st_CBlock,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing,Exterior2nd_AsbShng,Exterior2nd_AsphShn,Exterior2nd_Brk Cmn,Exterior2nd_BrkFace,Exterior2nd_CBlock,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Other,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,MasVnrType_BrkCmn,MasVnrType_BrkFace,MasVnrType_NA,MasVnrType_Stone,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_Po,ExterCond_TA,Foundation_BrkTil,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,BsmtQual_NA,BsmtQual_TA,BsmtCond_Fa,BsmtCond_Gd,BsmtCond_NA,BsmtCond_Po,BsmtCond_TA,BsmtExposure_Av,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_NA,BsmtExposure_No,BsmtFinType1_ALQ,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_NA,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_ALQ,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_NA,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_Floor,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,HeatingQC_Ex,HeatingQC_Fa,HeatingQC_Gd,HeatingQC_Po,HeatingQC_TA,CentralAir_N,CentralAir_Y,Electrical_FuseA,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,KitchenQual_Ex,KitchenQual_Fa,KitchenQual_Gd,KitchenQual_TA,GarageType_2Types,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageType_NA,MiscFeature_Gar2,MiscFeature_NA,MiscFeature_Othr,MiscFeature_Shed,MiscFeature_TenC,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,TotalSF,TotalBath,HouseAge,YearsSinceRemodel,TotalPorchSF,OutdoorSF,TotalBsmtFinished,TotalRooms,TotalPropertySF,HasGarage,HasBasement,HasPool,QualitySF,SalePrice
0,1,60,65.0,8450,1,0,3,3,2,7,5,2003,2003,196.0,706.0,0.0,150.0,856.0,856,854,0,1710,1.0,0.0,2,1,3,1,8,7,0,0,2003.0,2,2.0,548.0,3,3,2,0,61,0,0,0,0,0,0,0,2,2008,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,2566.0,3.5,5,5,61,61,706.0,11,3114.0,1,1,0,17962.0,208500.0
1,2,20,80.0,9600,1,0,3,3,2,6,8,1976,1976,0.0,978.0,0.0,284.0,1262.0,1262,0,0,1262,0.0,1.0,2,0,3,1,6,7,1,3,1976.0,2,2.0,460.0,3,3,2,298,0,0,0,0,0,0,0,0,5,2007,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,2524.0,2.5,31,31,0,298,978.0,9,2984.0,1,1,0,15144.0,181500.0
2,3,60,68.0,11250,1,0,2,3,2,7,5,2001,2002,162.0,486.0,0.0,434.0,920.0,920,866,0,1786,1.0,0.0,2,1,3,1,6,7,1,3,2001.0,2,2.0,608.0,3,3,2,0,42,0,0,0,0,0,0,0,9,2008,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,2706.0,3.5,7,6,42,42,486.0,9,3314.0,1,1,0,18942.0,223500.0
3,4,70,60.0,9550,1,0,2,3,2,7,5,1915,1970,0.0,216.0,0.0,540.0,756.0,961,756,0,1717,1.0,0.0,1,0,3,1,7,7,1,4,1998.0,1,3.0,642.0,3,3,2,0,35,272,0,0,0,0,0,0,2,2006,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,2473.0,2.0,91,36,307,307,216.0,10,3115.0,1,1,0,17311.0,140000.0
4,5,60,84.0,14260,1,0,2,3,2,8,5,2000,2000,350.0,655.0,0.0,490.0,1145.0,1145,1053,0,2198,1.0,0.0,2,1,4,1,9,7,1,3,2000.0,2,3.0,836.0,3,3,2,192,84,0,0,0,0,0,0,0,12,2008,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,3343.0,3.5,8,8,84,276,655.0,13,4179.0,1,1,0,26744.0,250000.0